[project]
name = "pebble.loghash"
version = "2.6.0"
description = "Pebble Log Hashing module"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"
