name: Build Docker image

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ARM_GNU_TOOLCHAIN_VERSION: 14.2.rel1
  ARM_GNU_TOOLCHAIN_PLATFORM: x86_64-arm-none-eabi
  EM_VERSION: 4.0.1
  EM_NODE_VERSION: 20.18.0_64bit

jobs:
  build-docker:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      # Preserve Buildx. Currently, we are using only linux/amd64
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./docker/Dockerfile
          tags: ghcr.io/${{ github.repository }}/pebble-firmware-waf:latest
          platforms: linux/amd64