name: Build Docker image

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ARM_GNU_TOOLCHAIN_VERSION: 14.2.rel1
  ARM_GNU_TOOLCHAIN_PLATFORM: x86_64-arm-none-eabi
  EM_VERSION: 4.0.1
  EM_NODE_VERSION: 20.18.0_64bit

jobs:
  build-docker:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Cache submodules
        id: cache-submodules
        uses: actions/cache@v4
        with:
          path: |
            third_party/cmsis_core/CMSIS
            third_party/hal_stm32/stm32-sdk
            third_party/nimble/mynewt-nimble
            third_party/ti_bt_sp/ti-service-packs
            third_party/hal_nordic/nrfx
            third_party/freertos/FreeRTOS-Kernel
            third_party/nanopb/nanopb
            third_party/tinymt/TinyMT
          key: ${{ runner.os }}-submodules

      - name: Init submodules
        if: steps.cache-submodules.outputs.cache-hit != 'true'
        run:
          git submodule update --init --recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          file: ./docker/Dockerfile
          tags: ghcr.io/${{ github.repository }}/builder:latest