name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ARM_GNU_TOOLCHAIN_VERSION: 14.2.rel1
  EM_VERSION: 4.0.1
  EM_CACHE_FOLDER: 'emsdk-cache'
  TEST_BOARD: 'snowy_bb2'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup emsdk cache
        id: cache-emsdk
        uses: actions/cache@v4
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: emsdk-${{env.EM_VERSION}}-${{ runner.os }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext gcc-multilib
          pip install -r requirements.txt
          wget --no-verbose "https://developer.arm.com/-/media/Files/downloads/gnu/${ARM_GNU_TOOLCHAIN_VERSION}/binrel/arm-gnu-toolchain-${ARM_GNU_TOOLCHAIN_VERSION}-x86_64-arm-none-eabi.tar.xz"
          sudo tar xf arm-gnu-toolchain-${ARM_GNU_TOOLCHAIN_VERSION}-x86_64-arm-none-eabi.tar.xz -C /opt
          echo "/opt/arm-gnu-toolchain-${ARM_GNU_TOOLCHAIN_VERSION}-x86_64-arm-none-eabi/bin" >> $GITHUB_PATH

      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Configure
        run: ./waf configure --board ${{env.TEST_BOARD}}

      - name: Run tests
        run: ./waf test
        continue-on-error: true

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: build/test/junit.xml
          annotate_only: true

      - name: Store failed test images
        uses: actions/upload-artifact@v4
        with:
          name: failed_diff_images
          path: build/test/tests/failed/*-diff.png
