name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ARM_GNU_TOOLCHAIN_VERSION: 14.2.rel1
  ARM_GNU_TOOLCHAIN_PLATFORM: x86_64-arm-none-eabi
  EM_VERSION: 4.0.1
  EM_NODE_VERSION: 20.18.0_64bit
  TEST_BOARD: 'snowy_bb2'

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      packages: read
    container:
      image: ghcr.io/${{ github.repository }}/builder:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache submodules
        id: cache-submodules
        uses: actions/cache@v4
        with:
          path: |
            third_party/cmsis_core/CMSIS
            third_party/hal_stm32/stm32-sdk
            third_party/nimble/mynewt-nimble
            third_party/ti_bt_sp/ti-service-packs
            third_party/hal_nordic/nrfx
            third_party/freertos/FreeRTOS-Kernel
            third_party/nanopb/nanopb
            third_party/tinymt/TinyMT
          key: ${{ runner.os }}-submodules

      - name: Init submodules
        if: steps.cache-submodules.outputs.cache-hit != 'true'
        run:
          git submodule update --init --recursive

      - name: Configure
        run: ./waf configure --board ${{env.TEST_BOARD}}

      - name: Run tests
        run: ./waf test
        continue-on-error: true

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: build/test/junit.xml
          annotate_only: true

      - name: Store failed test images
        uses: actions/upload-artifact@v4
        with:
          name: failed_diff_images
          path: build/test/tests/failed/*-diff.png
